#!/usr/bin/env bash
# Import this run's images into the octavia_studio catalogue.
# Safe to run unattended: importing pixels and creating a shoot
# record asserts nothing about what the images contain.
set -euo pipefail

cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py shoot create rt-test --name 'Generated by octavia-studio run OBS'

cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_000.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_001.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_002.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_003.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_004.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_005.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_006.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_007.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_008.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_009.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_010.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_011.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_012.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_013.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_014.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_015.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_016.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_017.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_018.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_019.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_020.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_021.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_022.png --shoot rt-test --source octavia-studio
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py import /home/user/Questlords-GAME/octavia-studio/runs/OBS/images/OBS_023.png --shoot rt-test --source octavia-studio

cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py --json asset list --shoot rt-test
cd /tmp/claude-0/-home-user-Questlords-GAME/6e3a84e4-e4b3-5fbe-83c5-dc2bc10c63a0/scratchpad/roundtrip && python3 octavia.py integrity --json
