"""Materialise a curated, captioned training set and emit a training config.

Two export targets:

  * ``lora``      — kohya_ss / sd-scripts layout: an image + matching .txt
                    caption per selected file, plus a dataset TOML and a
                    suggested hyperparameter block.
  * ``ipadapter`` — a small, deliberately diverse reference subset for
                    reference-conditioning without any training at all.

Source files are COPIED, never moved, and the source directory is never
written to.
"""
from __future__ import annotations

import json
import pathlib
import shutil
from collections import defaultdict
from typing import Any, Dict, List, Sequence

from training.ingest import ImageRecord


def _repeats_for(count: int, target: int) -> int:
    """kohya `repeats` so one epoch sees roughly ``target`` samples."""
    if count <= 0:
        return 1
    return max(1, round(target / count))


def export_lora(records: Sequence[ImageRecord], out_dir: pathlib.Path,
                cfg: Dict[str, Any]) -> Dict[str, Any]:
    trigger = cfg["identity"]["trigger_token"]
    class_token = cfg["identity"].get("class_token", "")
    train_cfg = cfg.get("training", {})
    selected = [r for r in records if r.selected and r.caption]

    if not selected:
        return {"error": "no selected, captioned images to export"}

    concept = f"{_repeats_for(len(selected), int(train_cfg.get('target_steps_per_epoch', 200)))}_{trigger}"
    img_dir = out_dir / "img" / concept
    img_dir.mkdir(parents=True, exist_ok=True)

    uncaptioned_templates = 0
    for r in selected:
        src = pathlib.Path(r.path)
        dest = img_dir / src.name
        if not dest.exists():
            shutil.copy2(src, dest)
        dest.with_suffix(".txt").write_text(r.caption + "\n", encoding="utf-8")
        if "TODO_" in r.caption:
            uncaptioned_templates += 1

    repeats = int(concept.split("_", 1)[0])
    buckets = defaultdict(int)
    for r in selected:
        buckets[r.bucket] += 1

    resolution = train_cfg.get("resolution", "896,1152")
    dataset_toml = f"""# Octavia LoRA dataset — generated by octavia-studio
[general]
shuffle_caption = true
caption_extension = ".txt"
keep_tokens = {int(train_cfg.get('keep_tokens', 1))}   # keep the trigger token fixed at position 0

[[datasets]]
resolution = [{resolution}]
batch_size = {int(train_cfg.get('batch_size', 1))}
enable_bucket = true
min_bucket_reso = {int(train_cfg.get('min_bucket_reso', 640))}
max_bucket_reso = {int(train_cfg.get('max_bucket_reso', 1536))}
bucket_reso_steps = 64

  [[datasets.subsets]]
  image_dir = "{img_dir.resolve()}"
  num_repeats = {repeats}
  class_tokens = "{trigger}{' ' + class_token if class_token else ''}"
"""
    (out_dir / "dataset.toml").write_text(dataset_toml, encoding="utf-8")

    hyper = {
        "_comment": "Suggested starting point, not a tuned recipe. Watch sample "
                    "images and stop when identity locks but flexibility remains.",
        "network_module": "networks.lora",
        "network_dim": int(train_cfg.get("network_dim", 32)),
        "network_alpha": int(train_cfg.get("network_alpha", 16)),
        "learning_rate": train_cfg.get("learning_rate", "1e-4"),
        "text_encoder_lr": train_cfg.get("text_encoder_lr", "5e-5"),
        "unet_lr": train_cfg.get("unet_lr", "1e-4"),
        "lr_scheduler": train_cfg.get("lr_scheduler", "cosine_with_restarts"),
        "lr_warmup_steps": int(train_cfg.get("lr_warmup_steps", 100)),
        "max_train_epochs": int(train_cfg.get("max_train_epochs", 10)),
        "save_every_n_epochs": int(train_cfg.get("save_every_n_epochs", 1)),
        "mixed_precision": train_cfg.get("mixed_precision", "bf16"),
        "optimizer_type": train_cfg.get("optimizer_type", "AdamW8bit"),
        "noise_offset": train_cfg.get("noise_offset", 0.03),
        "min_snr_gamma": int(train_cfg.get("min_snr_gamma", 5)),
        "_dataset_stats": {
            "selected_images": len(selected),
            "num_repeats": repeats,
            "approx_steps_per_epoch": len(selected) * repeats,
            "aspect_buckets": dict(buckets),
        },
        "_save_every_epoch_note": "Save every epoch and test each checkpoint. "
                                  "The best LoRA is usually NOT the last one — "
                                  "later epochs overfit and lose pose flexibility.",
    }
    (out_dir / "hyperparameters.json").write_text(json.dumps(hyper, indent=2), encoding="utf-8")

    manifest = [r.to_dict() for r in selected]
    (out_dir / "training_manifest.json").write_text(
        json.dumps({"trigger_token": trigger, "class_token": class_token,
                    "count": len(selected), "images": manifest}, indent=2),
        encoding="utf-8")

    return {
        "target": "lora",
        "out_dir": str(out_dir),
        "image_dir": str(img_dir),
        "exported": len(selected),
        "num_repeats": repeats,
        "steps_per_epoch": len(selected) * repeats,
        "aspect_buckets": dict(buckets),
        "placeholder_captions": uncaptioned_templates,
        "dataset_toml": str(out_dir / "dataset.toml"),
        "hyperparameters": str(out_dir / "hyperparameters.json"),
    }


def export_ipadapter(records: Sequence[ImageRecord], out_dir: pathlib.Path,
                     cfg: Dict[str, Any]) -> Dict[str, Any]:
    """Pick a small, deliberately spread reference subset.

    IPAdapter/InstantID work best with a handful of clean, varied face
    references — not the whole set. Selection takes the highest-quality
    member of each distinct near-duplicate cluster, so the subset spans
    different shots rather than stacking one look.
    """
    n = int(cfg.get("ipadapter", {}).get("subset_size", 12))
    selected = [r for r in records if r.selected]

    by_cluster: Dict[int, List[ImageRecord]] = defaultdict(list)
    for r in selected:
        by_cluster[r.cluster if r.cluster is not None else -1].append(r)

    picks: List[ImageRecord] = []
    for cid in sorted(by_cluster, key=lambda c: -len(by_cluster[c])):
        members = sorted(by_cluster[cid],
                         key=lambda r: (r.width * r.height, r.rms_contrast), reverse=True)
        picks.append(members[0])
        if len(picks) >= n:
            break
    # Top up from remaining images if there were fewer clusters than n.
    if len(picks) < n:
        chosen = {id(p) for p in picks}
        rest = sorted((r for r in selected if id(r) not in chosen),
                      key=lambda r: (r.width * r.height, r.rms_contrast), reverse=True)
        picks.extend(rest[: n - len(picks)])

    out_dir.mkdir(parents=True, exist_ok=True)
    for i, r in enumerate(picks):
        dest = out_dir / f"ref_{i:02d}_{pathlib.Path(r.path).name}"
        if not dest.exists():
            shutil.copy2(r.path, dest)

    return {
        "target": "ipadapter",
        "out_dir": str(out_dir),
        "exported": len(picks),
        "distinct_clusters": len(by_cluster),
        "note": "Point renderer.comfyui IPAdapter/InstantID nodes at this folder. "
                "No training required.",
    }
