#!/usr/bin/env python3
"""Makes the site ready for its production domain, https://quadcom.live.

    python3 site/tools/build-domain.py        (run after build-desks.py and build-catalog-page.py)

Writes, idempotently:
  every page   Canonical URL, Open Graph and Twitter card tags between <!--qc-meta--> markers, built from the
               page's own <title> and meta description, with the shared preview card assets/og-card.png
               (tools/build-og-card.mjs). Old og:/twitter: tags outside the markers are removed. 404 and offline
               pages are noindex and get no canonical or og:url.
  sitemap.xml  Every public route, as canonical URLs.
  robots.txt   Allows everything and points at the sitemap.
  _headers     Response headers for hosts that read this file (Cloudflare Pages, Netlify): security headers on
               every route; cross-origin isolation (COOP/COEP) on the desks, which lets the engine use its
               SharedArrayBuffer worker arena (it falls back to copies when a host cannot send headers); and
               no-cache on sw.js and the manifest so new builds reach returning visitors.
  CNAME        The custom domain, for GitHub Pages. Other hosts ignore it.
"""
import html, os, re

DOMAIN = "https://quadcom.live"
ROOT = os.path.join(os.path.dirname(__file__), "..")
CARD_ALT = "QuadCOM · Ever Next Phase: the QuadCOM mark beside the engraved Genesis Seal"
NOINDEX = {"404.html", "offline.html"}

def pages():
    out = []
    for dirpath, dirs, files in os.walk(ROOT):
        dirs[:] = sorted(d for d in dirs if d not in ("tools", "assets"))
        rel = os.path.relpath(dirpath, ROOT)
        for f in sorted(files):
            if f.endswith(".html") and (f == "index.html" or rel == "."):
                out.append(os.path.normpath(os.path.join(rel, f)))
    return out

def route(rel):
    if rel.endswith("index.html"):
        d = os.path.dirname(rel)
        return "/" if d in ("", ".") else "/" + d.replace(os.sep, "/") + "/"
    return "/" + rel

def attr(v):
    return html.escape(html.unescape(v), quote=True)

def meta_block(title, desc, url, indexable):
    tags = []
    if indexable:
        tags.append(f'<link rel="canonical" href="{url}">')
    tags += ['<meta property="og:type" content="website">', '<meta property="og:site_name" content="QuadCOM">',
             f'<meta property="og:title" content="{attr(title)}">', f'<meta property="og:description" content="{attr(desc)}">']
    if indexable:
        tags.append(f'<meta property="og:url" content="{url}">')
    tags += [f'<meta property="og:image" content="{DOMAIN}/assets/og-card.png">', '<meta property="og:image:width" content="1200">',
             '<meta property="og:image:height" content="630">', f'<meta property="og:image:alt" content="{attr(CARD_ALT)}">',
             '<meta name="twitter:card" content="summary_large_image">', f'<meta name="twitter:image:alt" content="{attr(CARD_ALT)}">']
    return "<!--qc-meta-->" + "".join(tags) + "<!--/qc-meta-->"

def stamp(rel):
    path = os.path.join(ROOT, rel)
    s = open(path, encoding="utf-8").read()
    s = re.sub(r"<!--qc-meta-->.*?<!--/qc-meta-->", "", s, flags=re.S)
    s = re.sub(r'<meta (?:property="og:[^"]*"|name="twitter:[^"]*")[^>]*>', "", s)
    s = re.sub(r'<link rel="canonical"[^>]*>', "", s)
    titles = re.findall(r"<title>(.*?)</title>", s, flags=re.S)
    descs = re.findall(r'<meta name="description" content="([^"]*)"', s)
    if len(titles) != 1 or len(descs) != 1:
        raise SystemExit(f"{rel}: expected one <title> and one description, found {len(titles)} and {len(descs)}")
    url = DOMAIN + route(rel)
    s = s.replace("</title>", "</title>" + meta_block(titles[0].strip(), descs[0], url, rel not in NOINDEX), 1)
    open(path, "w", encoding="utf-8").write(s)
    return route(rel)

def write(name, text):
    with open(os.path.join(ROOT, name), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)

HEADERS = """# Response headers for Cloudflare Pages and Netlify (GitHub Pages ignores this file; the site still works there,
# and the desks fall back from the shared worker arena to copies). Generated by tools/build-domain.py.
/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()
  X-Frame-Options: SAMEORIGIN
  Strict-Transport-Security: max-age=31536000

# Cross-origin isolation for the desks: unlocks SharedArrayBuffer for the engine's worker arena. Every desk
# subresource is same-origin; market data arrives by CORS fetch and WebSocket, which isolation allows.
/desk/*
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Embedder-Policy: require-corp

# New builds must reach returning visitors: the worker and manifest are always revalidated.
/sw.js
  Cache-Control: no-cache
/manifest.json
  Cache-Control: no-cache
"""

if __name__ == "__main__":
    routes = [stamp(rel) for rel in pages()]
    public = sorted(r for r in routes if not r.endswith(tuple(NOINDEX)))
    write("sitemap.xml", '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
          + "".join(f"  <url><loc>{DOMAIN}{r}</loc></url>\n" for r in public) + "</urlset>\n")
    write("robots.txt", f"User-agent: *\nAllow: /\n\nSitemap: {DOMAIN}/sitemap.xml\n")
    write("_headers", HEADERS)
    write("CNAME", DOMAIN.split("://", 1)[1] + "\n")
    print(f"{len(routes)} pages stamped · sitemap {len(public)} routes · robots.txt · _headers · CNAME")
