# QuadCOM site upgrade catalog, part A (areas A–H). Status codes:
#   S54 shipped in build 54 · S53 shipped in build 53 · N next (recommended)
#   D deferred (blocked; reason given) · R rejected (conflicts with site principles; reason given)
AREAS = {}
AREAS["A · ACCESSIBILITY"] = [
("S53","Keyboard focus rings on every link, button and input","2px gold outline, offset so it never merges with borders."),
("S53","Skip-to-content link on all content pages","First tab stop; targets <main id=main>."),
("S53","Buttons at least 44px tall, nav targets at least 38px","V54 keeps it: A–Z, footer links and phone nav 38px; TOP 44px."),
("S53","Reduced-motion users get no transitions or animations",""),
("S53","Muted grey raised from ~3:1 to ~6:1 contrast","--dimtxt #5c5e54 → #8f8f83."),
("S54","Decorative flow arrows hidden from screen readers","How-it-works no longer reads 'down arrow' seven times."),
("S54","Glossary search announces result counts politely","role=status: '3 of 40 terms match'."),
("S54","Glossary 'no match' state is spoken and shown","Previously the list silently went empty."),
("S54","Heading anchors carry descriptive aria-labels","'Link to 13 · WHAT IS GLIMMER?' instead of '#'."),
("S54","Desk gets a real (visually hidden) h1","Screen-reader users land on 'QuadCOM Bitcoin Desk'."),
("S54","Desk honours prefers-reduced-motion","Animations and transitions collapse to zero."),
("S54","Desk explains itself when JavaScript is off","noscript notice instead of a black screen."),
("S54","Deep-link targets are highlighted, not just scrolled to",":target border so the eye finds the term."),
("S54","Anchor links visible on touch devices","Hover-only reveal replaced by a 55% resting state on hover:none."),
("N","Glossary as a <dl> definition list","Better semantics for term/definition pairs; needs CSS remap."),
("N","Landmark labels for each content grid","aria-label on .qc-grid sections for rotor navigation."),
("N","Visible focus order audit across the desk command bar","Ensure VIEW→PERF→SEED→HALT tab order matches visual order."),
("N","HALT gets aria-pressed and a spoken state","Safety control should announce ARMED/HALTED."),
("N","Desk panel titles become real headings (h2)","Rotor navigation between panels."),
("N","Live price announcements rate-limited to 1 per 10s","aria-live on every tick floods VoiceOver."),
("N","Chart gets a text alternative summarising range and last price","Canvas is invisible to assistive tech."),
("N","VISION canvases get an on-demand data table","Same numbers as the render, readable by screen readers."),
("N","Colour is never the only carrier of TP/SL meaning in VISION","Add TP/SL text labels on the ring legend at all tiers."),
("N","Forced-colors (Windows high contrast) pass","Borders and focus must survive system colours."),
("N","Glossary search clear button labelled for AT","Native search clear is not announced everywhere."),
("N","Language of parts: mark 'Ever Next Phase' tagline as en","Trivial, but completes lang semantics."),
("N","Zoom to 200% without horizontal scroll on content pages","Verify with browser zoom, fix any fixed widths."),
("N","Text-spacing override test (WCAG 1.4.12)","Line/letter spacing overrides must not clip panels."),
("N","Motion toggle inside the desk, independent of OS setting",""),
("N","Screen-reader walkthrough script in README","So future builds can be re-checked the same way."),
("D","Desk pinch-zoom","Deferred: V43 decision D02 rejects it for the fixed full-screen cockpit; iOS ignores user-scalable=no anyway."),
("D","Full WCAG 2.2 AA audit of the desk","Needs a real VoiceOver/TalkBack session on devices."),
("D","Captions/transcripts for future video","No video content exists yet."),
("D","Haptic cues for HALT/SEED","Deferred per V43 D08: needs severity semantics first."),
("D","Audio alarms","Deferred per V43 D07: needs mute behaviour designed first."),
("R","Auto-reading every tape tick aloud","Rejected: overwhelms assistive tech; summarise instead."),
("R","Hiding the desk from assistive tech entirely","Rejected: operators using AT must still reach HALT."),
("R","Colour-only bull/bear balance","Rejected: text values must stay beside the bar."),
("R","Overlay accessibility widgets","Rejected: third-party overlays add weight and rarely fix real issues."),
("R","Disabling focus outlines for aesthetics","Rejected: keyboard users need them."),
]
AREAS["B · TYPOGRAPHY & READABILITY"] = [
("S53","Site type scale raised from 5–9px to 9–17px",""),
("S53","Search input at 16px","iOS no longer auto-zooms on focus."),
("S53","Paragraph line-height 1.6",""),
("S54","Balanced wrapping for titles and headings","text-wrap: balance."),
("S54","Pretty wrapping for paragraphs","Fewer orphans (text-wrap: pretty)."),
("S54","Paragraph measure capped at 68ch","Comfortable reading line length."),
("S54","Gold text selection colour","Selection stays legible on dark panels."),
("S54","Desk cell labels no longer clipped at the top","line-height 1.08 → 1.35; CASH/SIDE/ENTRY now render whole."),
("S54","Print stylesheet: black on white, no chrome","Learn and glossary print as readable documents."),
("N","Tabular numerals everywhere numbers align","font-variant-numeric: tabular-nums on metrics."),
("N","Uniform letter-spacing tokens (tight/normal/wide)","Replace ad-hoc .06/.08/.12/.14/.16em values."),
("N","Type tokens as CSS variables (--t-xs … --t-xl)","One place to tune the scale."),
("N","Minimum 7px for desk micro-labels on phones","Some ALL-view labels render at 3.5px."),
("N","Desk ALL view: hide lowest-priority micro text instead of shrinking it","Density by omission, not by illegibility."),
("N","Consistent casing policy (caps for labels, sentence case for prose)",""),
("N","Hyphenation for long glossary words on narrow screens","hyphens:auto with lang=en."),
("N","Use en/em dashes consistently in copy",""),
("N","Avoid all-caps paragraphs (only labels are caps)",""),
("N","Headline sizes step by a fixed ratio (1.25)",""),
("N","Differentiate h2 and h3 in glossary by size, not only colour",""),
("N","Clamp() fluid sizes for kicker and sub on tablets",""),
("N","Line-height tokens for dense vs prose contexts",""),
("N","Ellipsis tooltips (title=) on truncated desk values","'$10,…' should reveal the full value."),
("N","Truncated panel titles get a full-title tooltip","e.g. 'MICROSTRUCTURE · A…'."),
("S56","Glossary term highlight of matched text","<mark> around the query."),
("N","Readable monospace fallback stack test on Windows","Consolas vs Menlo metrics differ."),
("N","Tight-leading audit on every 'small' in the desk","Same clipping class as the fixed cell labels."),
("N","Numeric formatting: thin space thousands on wide screens","Optional; keep commas on phones."),
("N","Currency symbol consistency (US$ vs $)","Desk mixes both."),
("N","Percent formatting: fixed decimals per field",""),
("D","Custom brand typeface","Deferred: V43 D06 rejects remote fonts; would need a self-hosted licence."),
("D","Variable-font optical sizing","Depends on a custom typeface."),
("D","Localised number formats","Deferred until the site ships another locale."),
("D","Right-to-left support","No RTL locale planned."),
("R","Text rendered into images","Rejected: unsearchable, inaccessible, blurry on zoom."),
("R","Sub-9px body text on public pages","Rejected: the V52 defect this catalog started from."),
("R","Light-grey-on-black 'luxury' low contrast","Rejected: fails WCAG contrast."),
("R","Justified text on narrow screens","Rejected: rivers of space in monospace."),
("R","Remote font CDN","Rejected: V43 D06, offline reliability."),
("R","Auto-shrinking text to fit panels below legibility","Rejected: clip or wrap instead."),
]
AREAS["C · LAYOUT & RESPONSIVE"] = [
("S53","Desk on screens ≥900px scales the phone-tuned cockpit","No more 2.5–3px text on desktops."),
("S53","Desk runtime build stamp matches its CSS (52)","195 dormant layout/skin rules now apply; views switch again."),
("S53","iPhone landscape header fits all 10 controls","HALT no longer wraps onto a clipped row."),
("S53","iPhone portrait SITE button moved beside the price","Previously on a hidden third row."),
("S53","Desktop header lays out every visible control",""),
("S53","Site nav wraps instead of hiding in an invisible scroll strip",""),
("S54","Narrow phones: nav becomes a tidy 4-column grid","Replaces three ragged wrapped rows."),
("S54","Sticky header no longer covers deep-link targets","scroll-padding 96px, 150px on phones."),
("S54","Footer reserves room for the floating TOP button",""),
("S54","Explicit image dimensions on logo and glyph","Prevents layout shift while images load."),
("N","Tablet (768–1024) content grid at 2 columns","Currently jumps from 1 to 3."),
("N","Desk: dedicated tablet portrait layout","1024×1366 reuses phone portrait proportions."),
("N","Container queries for panels instead of viewport queries",""),
("N","Desk ALL view 'consensus' panel overflow","Pre-existing since V43; content exceeds its cell."),
("N","Safe-area insets on the site header for landscape iPhones",""),
("N","Max content width token shared by header and main",""),
("N","Home: LIVE FIELD panel height matches ENTRY SURFACE on desktop",""),
("N","How-it-works flow as a horizontal rail on wide screens",""),
("N","Data page: two-column provenance legend on desktop",""),
("N","Glossary: two-column term grid on wide screens",""),
("N","Learn: card numbering visible in a left gutter on desktop",""),
("N","Consistent 4/8px spacing scale tokens",""),
("N","Remove !important chains in desk CSS where specificity suffices","Nine historical style layers fight each other."),
("N","Consolidate desk style layers V14–V51 into one sheet","Same rendered result, far less override debt."),
("N","Foldable/dual-screen posture check",""),
("N","Desk: remember last view per orientation",""),
("N","Desk: landscape CORE gives the chart more width on 16:9 desktops",""),
("N","Desk: FLEET view wall panel minimum width",""),
("N","Desk desktop scaling: verify in Safari and Firefox","Chromium verified; others untested."),
("N","Fallback for browsers without CSS zoom","Firefox < 126: transform-based scaling."),
("D","Desk multi-window layouts","Needs a layout schema (V43 D10)."),
("D","User-reorderable panels","Deferred per V43 D10: durable layout schema and reset path first."),
("D","Individual panel maximisation","V43 D11 candidate; needs gesture design."),
("D","Apple Watch / widget surfaces","Out of scope for the web build."),
("R","Horizontal panel carousel","Rejected per V43 D01: swipe ambiguity beside charts."),
("R","Auto-rotating views","Rejected per V43 D04: context must not move by itself."),
("R","Infinite scroll on content pages","Rejected: pages are short and finite."),
("R","Fixed 1440px desktop canvas","Rejected: must reflow."),
("R","Hiding HALT on small screens to save space","Rejected: safety control is always reachable."),
("R","Page-level horizontal scrolling on phones","Rejected: V43 validation target."),
]
AREAS["D · NAVIGATION & WAYFINDING"] = [
("S54","Previous / next page links on every content page","Content-page order; the desk stays one tap away in the nav."),
("S54","Footer navigation row",""),
("S54","Back-to-top button on long pages","Appears after scrolling ~1.5 screens; hidden otherwise."),
("S54","Deep links to every Learn card","#what-is-glimmer etc.; copy on tap."),
("S54","Deep links to every glossary term",""),
("S54","A–Z jump index on the glossary",""),
("S54","'/' focuses glossary search from anywhere on the page","Hint shown in the placeholder."),
("S54","Esc clears the glossary filter",""),
("S54","Glossary query kept in the URL (?q=)","Shareable, survives reload."),
("S54","Following a deep link to a filtered-out term clears the filter",""),
("S54","Branded 404 page with routes onward","Static hosts serve /404.html."),
("S53","Desk SITE button returns to the public site on every layout",""),
("N","Breadcrumb line under the kicker",""),
("N","'You are here' in the footer nav",""),
("N","Learn: in-page table of contents",""),
("S56","Glossary terms auto-linked from Learn and Data copy","First mention links to the definition."),
("N","Related-terms links under each glossary entry",""),
("N","Desk: '?' opens a keyboard-shortcut sheet",""),
("N","Desk keyboard shortcuts: V (view), H (halt)","HALT shortcut must need confirmation."),
("N","Search across all pages, not just the glossary","Static index built at release."),
("N","Recently viewed terms (local only)",""),
("N","Desk view name in the document title","'Bitcoin Desk · VISION · QuadCOM'."),
("N","Return-to-desk banner on content pages when a desk session is saved","Local state only, clearly labelled."),
("N","Desk: remember the last glossary term an operator opened",""),
("N","Home: route cards for each audience (operator, curious, technical)",""),
("N","Nav: highlight parent for nested future routes",""),
("N","Anchor copy confirmation announced to screen readers",""),
("N","Pager shows page purpose, not just its name",""),
("S56","Footer build link to the upgrade catalog",""),
("N","Consistent trailing-slash URLs and redirects",""),
("D","sitemap.xml","Needs the production domain for absolute URLs."),
("D","Canonical URLs","Needs the production domain."),
("D","Versioned docs per build","Needs a hosting decision."),
("D","Multi-desk routes (/desk/eth/…)","Only the Bitcoin desk exists."),
("D","Account area","No accounts exist; none planned."),
("R","Mega-menu","Rejected: seven routes do not need one."),
("R","Hamburger hiding all routes on phones","Rejected: the 4-column grid keeps them visible."),
("R","Hijacked scrolling / scroll-jacking",""),
("R","Modal newsletter prompts",""),
("R","Opening internal links in new tabs",""),
]
AREAS["E · CONTENT — LEARN"] = [
("S54","13 · What is GLIMMER?",""),
("S54","14 · What is VISION?",""),
("S54","15 · What does 'inferred' mean?","Grounds the PRESSURE label."),
("N","16 · How to read the risk cone","P5/P50/P95 and why √time spreads it."),
("N","17 · How to read the trade-odds ring",""),
("N","18 · What is holdout validation?",""),
("N","19 · What is overfitting, with the sweep as the example",""),
("N","20 · What 'effective independent PICOs' tells you",""),
("N","21 · What the desk does when offline",""),
("N","22 · What HALT and SEED do","Operational semantics, engine-accurate."),
("N","23 · What PERF modes change",""),
("N","24 · Reading the three desk views",""),
("N","25 · What the skins are (REGALIA / AURUM / OFF)","Ornament only; no data meaning."),
("N","Worked example: one tick from tape to Best Singular Trade",""),
("N","Common misreadings box on each card","e.g. DIST is not SELL."),
("N","'Observed / derived / inferred / model' tag on every Learn card",""),
("N","Operator checklist before trusting the Best Singular Trade",""),
("N","Glossary cross-links in every card",""),
("N","Short diagram per card (SVG, themed)",""),
("N","Printable one-page operator primer",""),
("N","Learn progress (local) — cards read",""),
("N","Reading-level pass on all copy",""),
("N","Consistent 'Desk' capitalisation",""),
("N","Card order: concepts before modes before outputs",""),
("N","Link each card to the desk panel it explains","Deep link with ?view= where relevant."),
("N","FAQ: why many processors instead of one model",""),
("N","FAQ: why no live values on public pages",""),
("N","FAQ: what the Crown is not",""),
("S56","Explain CFD100 and 100:1 labels seen in the desk brand line",""),
("N","Explain INT RMSE and PIV in the trade panel header",""),
("D","Video walkthroughs","No recording pipeline yet."),
("D","Interactive tutorial overlay on the desk","Needs stable selectors across builds."),
("D","Quizzes / certification","No accounts."),
("D","Translated Learn pages","No locale planned."),
("D","Historical case studies","Needs archived real data with provenance."),
("R","Performance claims or return figures","Rejected: nothing on public pages may be fabricated."),
("R","'Guaranteed' or predictive marketing language",""),
("R","Testimonials","Rejected: unverifiable."),
("R","Screenshots presented as live","Rejected: QA frames must be labelled as such."),
("R","Gamified streaks","Rejected: not an operator tool."),
]
AREAS["F · CONTENT — GLOSSARY"] = [
("S54","Sorted A–Z","V52 listed ACC before ABSORB."),
("S54","GLIMMER",""),("S54","VISION",""),("S54","ENVELOPE",""),("S54","PRESSURE (INFERRED)",""),
("S54","HOLDOUT",""),("S54","WEBGPU","Explicitly not native Metal."),("S54","P0–P3",""),
("S54","EFFECTIVE INDEPENDENT PICOS",""),
("S56","RISK CONE",""),("S56","TRADE ODDS",""),("N","SHARPE (HOLDOUT)",""),("S56","BOOTSTRAP",""),
("S56","CALIBRATION (GLIMMER)","Backend must match the JS reference."),("S56","BACKEND",""),("S56","TIER (VISION)",""),
("N","REGALIA",""),("N","AURUM",""),("N","HALT",""),("N","SEED",""),("N","PERF",""),
("N","VPIN",""),("N","TOXICITY",""),("N","BOOK SLOPE",""),("N","QUEUE IMBALANCE",""),
("N","PIVOT HORIZON",""),("N","INTEGRITY","Engine-defined; say so."),("S56","CFD100",""),
("N","Pronunciation / expansion for every acronym",""),("N","'See also' links between terms",""),
("N","Class tag (observed/derived/inferred/model) on every term",""),
("D","Glossary API (JSON)","Needs a hosting decision; trivial to emit at build time later."),
("D","Term history (which build introduced it)","Needs release tooling."),
("R","Definitions that restate the term","Rejected: every entry must add information."),
("R","Trading advice inside definitions",""),
("R","Inventing exact formulas the engine does not expose","Rejected: 'engine-defined' is the honest answer."),
("R","Hiding engine-defined caveats to look authoritative",""),
("R","Auto-generated definitions without review",""),
("R","Pop-up definitions that cover the desk",""),
("R","Crowd-edited glossary","Rejected: terminology must match the engine."),
]
AREAS["G · CONTENT — HOW IT WORKS & DATA PROVENANCE"] = [
("S54","Data: 05 · GLIMMER compute output class","Model output; calibrated against the JS reference."),
("S54","Offline page states that nothing offline is live",""),
("N","How-it-works: add GLIMMER as a side-rail beside the processor field",""),
("N","How-it-works: mark where VISION reads from",""),
("N","Flow nodes linked to their glossary terms",""),
("N","Data: per-field provenance table for every desk panel",""),
("N","Data: feed fallback order explained (WS → REST → last known)",""),
("N","Data: what 'RT FALLBACK' in the desk header means",""),
("N","Data: history-gap handling (UNRESOLVED / PARTIAL / COMPLETE)",""),
("S56","Data: storage — what stays on the device and what never leaves",""),
("N","Data: how long local state is kept",""),
("N","Data: clearing local desk state safely",""),
("N","Provenance colours identical across Data, How-it-works and desk",""),
("N","Provenance tag component reused on every page",""),
("N","Show the observation boundary in the desk itself",""),
("N","Explain simulated vs real positions explicitly","Paper/lesson positions vs fleet books."),
("N","Explain 'CALIBRATING' / 'WARMING' states",""),
("N","Explain STALE results after resume",""),
("N","Document exchange sources the desk connects to",""),
("N","Document what happens when sources disagree",""),
("N","Data page: 'last reviewed' build stamp",""),
("N","Provenance diagram as accessible SVG",""),
("N","Worked provenance example: ATR from raw ticks",""),
("N","Worked provenance example: Crown change",""),
("N","Worked provenance example: GLIMMER trade odds",""),
("N","Caveats section: known limitations per class",""),
("S56","Link the upgrade catalog from the Data page",""),
("D","Live feed-age widget on public pages","Deferred: needs a public data service; must not be simulated."),
("D","Public status page","Needs hosting/monitoring."),
("D","Third-party data attribution page","Needs final data-source contracts."),
("D","Audit log export","Needs an engine API."),
("R","Showing example live values on public pages","Rejected: the site's founding rule."),
("R","Latency or uptime claims without measurement",""),
("R","Blurring observed and model output for simplicity",""),
("R","Marketing-style accuracy percentages",""),
("R","Hiding fallback state from operators",""),
("R","Calling inferred values 'readings'",""),
("R","Claiming native Metal / hardware access","Rejected: WebGPU only."),
("R","Temperature or wattage displays","Rejected: not exposed to web pages."),
("R","Silent data backfill presented as live",""),
]
AREAS["H · VISUAL IDENTITY & SKIN"] = [
("S53","REGALIA skin installed site-wide","Corners, mandala watermark, filigree, carbon and brushed-gold buttons."),
("S53","Single texture location (/assets/textures) for site and desk",""),
("S53","Logo no longer sits in a black box","mix-blend-mode: lighten."),
("S54","Mandala watermark scaled down and pushed off text","150px, anchored past the corner."),
("S54","Anchor '#' marks styled in dim gold",""),
("S54","Target highlight in hot gold",""),
("N","Transparent logo PNG instead of blend-mode","Removes a compositing layer."),
("N","SVG logo for crisp rendering at every size",""),
("N","Skin toggle on public pages (currently desk-only)",""),
("N","AURUM variant for public pages",""),
("N","Paint mandala layers beneath the dark gradient","Guarantees skin never touches text contrast."),
("N","WebP/AVIF texture variants","Smaller downloads; PNG fallback."),
("N","Texture preload on the desk route only",""),
("N","Consistent corner size tokens (site 20px, desk 18px)",""),
("N","Brand colour tokens shared between site and desk CSS",""),
("N","Focus ring colour as a token",""),
("N","Panel elevation tokens",""),
("N","Dark-mode-only declared (color-scheme: dark) on desk too",""),
("N","Theme-color per route",""),
("N","Favicon SVG with dark/light variants",""),
("N","Open Graph image (1200×630) in brand style","Needs absolute URL → see SEO."),
("N","Print logo variant",""),
("N","Home: entry glyph gets the mandala as a halo",""),
("N","Icon set for provenance classes",""),
("N","Unified button component across site and desk",""),
("N","Desk badge 'V51' vs build 54","Visible desk wording: awaiting owner approval."),
("D","Custom illustration set","Needs an illustrator/brief."),
("D","Motion identity (logo reveal)","Must respect V43 D03 and reduced motion."),
("D","Light theme","Brand is dark-native; needs full token pass first."),
("D","Seasonal skins","Low value until the token system exists."),
("R","Constant animated glow","Rejected per V43 D03: OLED contrast and frame stability."),
("R","Textures inside the chart field","Rejected: data ink stays on black."),
("R","Neon gradients behind numbers",""),
("R","Skeuomorphic bevels on every control",""),
("R","Autoplaying background video",""),
("R","Parallax on content pages",""),
("R","Stock imagery",""),
("R","Brand name of the reference skin anywhere","Rejected by owner instruction."),
("R","Watermarks over data values",""),
("R","Heavy drop shadows that blur panel edges",""),
]
