# QuadCOM site upgrade catalog, part B (areas I–O). Status codes as in catalog_a.py.
AREAS = {}
AREAS["I · SITE ↔ DESK INTEGRATION"] = [
("S53","GLIMMER modules installed in the desk","V52 referenced them but shipped without them."),
("S53","VISION view renders instead of an empty panel",""),
("S53","Desk uses the site's single service worker","Its ./sw.js registration pointed at a missing file."),
("S53","Desk icons, splash images and manifest resolve","All 404 in V52."),
("S53","Desk tab title 'Bitcoin Desk · QuadCOM'","Was a lone '❖'."),
("S53","Desk texture base configurable (data-qc-texture-base)","glimmer-vision.js works in any folder."),
("S53","Absolute GLIMMER script paths","No dependency on a trailing-slash redirect."),
("S53","Removed name purged from desk OPFS file names","Write-only files; no data lost."),
("S54","Glossary defines GLIMMER, VISION, ENVELOPE, PRESSURE, P0–P3, HOLDOUT and WEBGPU","Telemetry rows such as WORKERS and FRAME are next (see F)."),
("S54","Learn explains GLIMMER, VISION and 'inferred'",""),
("N","Desk panel titles link to their glossary term (long-press)",""),
("N","'?' on any desk panel opens the matching Learn card",""),
("N","Public pages show 'last desk session on this device: n min ago'","Local timestamp only; no values."),
("N","Shared skin preference between site and desk","Site honours OFF; add AURUM."),
("N","Desk ?view= links from Learn cards",""),
("N","Desk remembers it was opened from a Learn card and offers a way back",""),
("N","One shared CSS token file for site and desk",""),
("N","One source for glimmer*.js (build copies from quadcom/)","Today they are byte-identical copies."),
("N","Release script that stamps the same build number everywhere",""),
("N","Desk visual-audit results published to a QA page at release",""),
("N","Site pages lint that fails on any removed/forbidden word",""),
("N","Desk exposes a read-only JSON of its public-safe state for the site","Needs an explicit whitelist."),
("N","Desk handles /desk/bitcoin (no slash) gracefully","Host redirect or a tiny index shim."),
("N","Desk error states link to the Data page explanation",""),
("N","Single manifest shared by site and desk (done) — add desk shortcut icon",""),
("N","Site footer shows desk build alongside site build",""),
("N","Consistent HALT semantics documented on both sides",""),
("N","Glossary search from inside the desk",""),
("N","Desk diagnostics console link to the catalog",""),
("N","Deep-link to VISION from GLIMMER glossary term",""),
("D","Server-side desk state sync","Browser-owned state is policy (V43 D09)."),
("D","Cross-device desk handoff","Needs accounts/sync; conflicts with local-first policy."),
("D","Embedding the desk in content pages","Needs a lightweight read-only renderer."),
("D","Desk notifications to the site","Needs a push service."),
("R","Public pages reading the desk's full local state","Rejected: 2000-PICO state is megabytes; privacy by default."),
("R","Showing desk values on public pages as live","Rejected: provenance rule."),
("R","Two service workers fighting over scope","Rejected: the V52 defect fixed in V53."),
("R","iframe-embedding the desk on the home page","Rejected: doubles runtime cost."),
("R","Tracking pixels to link site and desk sessions",""),
("R","Forcing the desk to open on site entry",""),
]
AREAS["J · DESK UX"] = [
("S53","All four views switch correctly again","The '43'/'52' stamp mismatch disabled them."),
("S53","No header controls clipped on iPhone portrait or landscape",""),
("S53","No header controls clipped on desktop",""),
("S54","Cell labels no longer clipped",""),
("S54","Reduced-motion support",""),
("S54","noscript explanation",""),
("N","HALT confirmation state visible at a glance (colour + text)",""),
("N","VIEW button shows the next view, not only the current one",""),
("N","Long-press VIEW to pick a view directly",""),
("N","PERF mode explained in a tooltip",""),
("N","SEED confirmation to avoid accidental reseeding",""),
("N","Empty-chart state explains 'waiting for feed' instead of blank black",""),
("N","Price freshness indicator next to the price (age in s)","Observed field; honest."),
("N","ALL view: tap a panel to focus it",""),
("N","FLEET view: search a PICO by number",""),
("N","Leaderboard: sticky header row",""),
("N","Trade panel: copy levels to clipboard",""),
("N","Horizon rail labels readable at 390px",""),
("N","Stress matrix axes labelled",""),
("N","Scenario cube axes labelled",""),
("N","Microstructure bars get min/max markers",""),
("N","Consistent '—' for unknown values",""),
("N","'ENGINE ERR' badge links to diagnostics",""),
("N","Orientation change keeps scroll/selection",""),
("N","Resume banner after long background: 'data from n min ago'",""),
("N","Operator notes (local) per session",""),
("N","Undo last SEED within 5 seconds",""),
("N","Keyboard control for every command",""),
("N","Diagnostics console readable (currently 5px)",""),
("N","'consensus' panel overflow in landscape ALL","Pre-existing since V43."),
("D","Replay scrubber","V43 D12 candidate; needs history controls."),
("S56","Multi-asset desk","Bitcoin, Dogecoin, XRP and Litecoin desks generated from one engine; state isolated per desk."),
("D","Order routing","Out of scope: the desk is interpretive."),
("D","Alerts","Needs D07/D08 semantics first."),
("R","One-tap real trading from the Best Singular Trade","Rejected: interpretive output is not an order ticket."),
("R","Hiding risk panels to simplify","Rejected: loss control is core."),
("R","Confetti or celebratory animation on wins",""),
("R","Sound on every tick",""),
("R","Auto-SEED on load",""),
("R","Pinch-zoom cockpit","Rejected per V43 D02."),
]
AREAS["K · GLIMMER & VISION"] = [
("S53","GLIMMER live in the public desk",""),
("S53","VISION renders (WebGPU → WebGL2 → Canvas 2D)",""),
("S53","GLIMMER header rule yields to device-tuned iPhone layouts",""),
("N","VISION data-table fallback for screen readers",""),
("N","VISION export as PNG (local download)",""),
("N","Risk cone: show the observed price path overlaid",""),
("N","Trade odds: show how odds change with horizon",""),
("N","Holdout map: axis tick labels",""),
("N","Fleet independence: highlight the most crowded PICO",""),
("N","GLIMMER sheet: explain each row inline",""),
("N","GLIMMER: persist calibration results per device",""),
("N","GLIMMER: expose results to the Data page on this device only",""),
("N","WebGPU canvas presentation: retry after browser update","Currently banned per session after an early loss."),
("N","VISION tier override (operator can force MED)",""),
("N","GLIMMER budget graph (last 60 s)","Shows envelope and use; browser-observable only."),
("N","Sweep: confidence band on holdout Sharpe",""),
("N","Cone: coverage progress indicator",""),
("N","Odds: stale marker when trade changes",""),
("N","Correlation: cluster view of crowded PICOs",""),
("N","Worker pool size shown with reason (reserve policy)",""),
("N","Unit tests for kernels in CI (node)","JS reference kernels are pure functions."),
("N","Golden-image tests for VISION shaders","Offscreen WGSL + GLSL render compared per build."),
("N","GLIMMER telemetry export (JSON download)",""),
("N","Budget respects Low Power Mode heuristics",""),
("N","VISION colour-blind palette option",""),
("N","Cone horizons configurable (15m/1h/4h/24h)",""),
("N","GLIMMER docs page on the public site",""),
("N","Compute Pressure API support where available","Already read; surface it in VISION tier choice."),
("D","WebNN acceleration","Not broadly available; must be feature-detected first."),
("D","WebGPU on the ambient/wall renderers","Wall/ambient are WebGL2; migrate only with measured wins."),
("S58","SharedArrayBuffer data path for workers","_headers sends COOP/COEP on each desk route; desks become cross-origin isolated and GLIMMER reports SharedArrayBuffer (verified with tools/qa/serve.py)."),
("D","Real-device iPhone benchmark table","Needs devices."),
("R","Fake GPU utilisation %","Rejected: not exposed by browsers."),
("R","Temperature readouts","Rejected: never fabricated."),
("R","Running compute while hidden","Rejected: suspends on visibility change."),
("R","Burning cycles to raise utilisation numbers","Rejected: work must produce value."),
("R","Claiming native Metal access","Rejected: WebGPU only."),
("R","Constant shimmer animation","Rejected: brief reveal only."),
("R","Disabling calibration for speed","Rejected: correctness first."),
("R","Unbounded worker count","Rejected: reserve for browser and OS."),
]
AREAS["L · PERFORMANCE"] = [
("S53","Service worker caches only good same-origin responses",""),
("S54","Stale-while-revalidate for assets","Deploys reach returning visitors on the next load."),
("S54","decoding=async on site-page images","Desk images are next."),
("S54","Image dimensions prevent layout shift on site pages","Desk images are next."),
("N","Compress textures (mandala 110KB → WebP ~35KB)",""),
("S56","Resize logo PNG for its display sizes (632KB source)","Site pages use 96px (5KB) and 640px copies; the desk keeps the source."),
("N","Preconnect hints for exchange endpoints on the desk route",""),
("N","Desk inline CSS split: critical vs deferred",""),
("N","Remove dead style layers from the desk","Hundreds of overridden rules."),
("N","Lazy-load VISION module until the view is opened",""),
("N","Content-visibility: auto for glossary terms",""),
("N","Font-display irrelevant (system fonts) — document it",""),
("S58","HTTP caching headers guide for the host","_headers: no-cache on sw.js and the manifest; README explains hosts."),
("N","Brotli pre-compression at release",""),
("N","Budget: home page < 200KB transferred",""),
("N","Budget: desk first render < 1.5s on iPhone 13",""),
("N","Measure INP on the desk command bar",""),
("N","Throttle desk DOM writes when hidden (already) — document",""),
("N","Avoid layout thrash in desk render loop","Batch reads/writes."),
("N","OffscreenCanvas for the price chart",""),
("N","Idle-time prefetch of Learn from Home",""),
("N","Module preload for glimmer.js",""),
("N","Trim unused glossary JS on other pages",""),
("N","Size-limit check in release script",""),
("N","Lighthouse CI on each build",""),
("N","Avoid backdrop-filter on low-end devices",""),
("N","Reduce box-shadow layers on desk panels",""),
("N","Texture sprites to cut requests",""),
("D","HTTP/3 and CDN","Hosting decision."),
("D","Edge caching of the desk shell","Hosting decision."),
("D","Real-user monitoring","Needs a privacy-respecting service."),
("R","Third-party analytics scripts","Rejected: weight and privacy."),
("R","Inlining every texture as base64","Rejected: defeats caching."),
("R","Minifying away all comments in source","Rejected: repo stays readable; minify at release only."),
("R","Preloading every route on first visit","Rejected: wasteful on mobile data."),
("R","Removing the service worker to 'avoid staleness'","Rejected: fixed properly instead."),
("R","Framework rewrite","Rejected per V43 D05."),
("R","Web font for icons",""),
("R","Polling APIs faster than they update",""),
("R","Autoplay media",""),
]
AREAS["M · OFFLINE, PWA & RELIABILITY"] = [
("S53","One missing file no longer aborts service-worker install",""),
("S53","Offline navigation ignores query strings","?view= desk links open offline."),
("S53","Redirected responses are never cached",""),
("S53","Manifest splits 'any' and 'maskable' icons","V52 declared one icon as both."),
("S54","Honest offline page for unvisited routes","Instead of silently showing Home."),
("S54","404 and offline pages precached",""),
("S54","App shortcuts: Desk, Glossary, Learn",""),
("S54","Cache name bumped to v54",""),
("N","'Update available — reload' toast when a new worker waits",""),
("N","Offline indicator in the site header",""),
("N","Background sync for queued desk checkpoints",""),
("N","Storage quota warning in the desk",""),
("N","Persistent storage request explained to the user",""),
("N","Manifest screenshots for richer install UI",""),
("S58","Manifest id/scope audit after hosting move","id, start_url and scope are / at the domain root."),
("N","Clear-site-data button on the Data page",""),
("N","Offline page lists cached routes",""),
("N","Versioned asset URLs at release",""),
("N","Service worker unit tests (fetch routing)",""),
("N","Navigation preload",""),
("N","Periodic cache cleanup of stale entries",""),
("N","Handle desk launch from the home-screen with stale shell",""),
("N","Error boundary around GLIMMER init","Already graceful; add a visible note."),
("N","Recovery link when OPFS is unavailable",""),
("N","Test in iOS standalone mode after each build",""),
("N","Test Android install + maskable icon crop",""),
("N","Test offline after 7 days (iOS eviction)",""),
("N","Export/import desk state file",""),
("D","Push notifications","Needs a server and consent design."),
("D","Periodic background sync","Limited browser support."),
("D","Web Share Target","No sharing use case yet."),
("D","File handling (open .qc files)","No file format defined."),
("R","Pretending to be live while offline","Rejected: provenance."),
("R","Caching error pages",""),
("R","Two workers with overlapping scope",""),
("R","Infinite retry loops on failed fetches",""),
("R","Silent data loss on eviction",""),
("R","Forcing install prompts",""),
("R","Background compute when the app is hidden",""),
("R","Clearing user state on update",""),
]
AREAS["N · SEO, SHARING & METADATA"] = [
("S53","Meta description on every page",""),
("S53","Favicons and apple-touch-icon on every page",""),
("S54","Open Graph title/description/type/site_name",""),
("S54","Twitter summary card",""),
("S54","robots.txt",""),
("S54","Build 54 stamped in every footer",""),
("N","Unique, specific descriptions per Learn card when deep-linked",""),
("N","Title pattern: page · QuadCOM (consistent casing)",""),
("N","Structured data: WebSite + DefinedTermSet for the glossary",""),
("N","hreflang when locales exist",""),
("N","Alt text review for every image",""),
("N","Human-readable URLs for Learn cards",""),
("N","Share button on glossary terms (Web Share API)",""),
("N","Short link format for terms (/g/atr)",""),
("N","Humans.txt / credits",""),
("N","security.txt","Needs a contact address."),
("N","RSS/Atom for build notes",""),
("N","Changelog page",""),
("S56","Upgrade catalog published as a page","/catalog/ renders both catalogs with search and a status filter."),
("S56","noindex on offline/404 pages",""),
("N","Descriptive link text audit (no 'click here')",""),
("N","Heading outline audit per page",""),
("N","Meta theme-color matches header per route",""),
("N","Apple web-app title per route",""),
("S58","Twitter/OG image alt text","og:image:alt and twitter:image:alt on every page."),
("N","Consistent brand casing in titles (QuadCOM vs QUADCOM)",""),
("S56","Remove duplicate titles (Home and QuadCOM pages share one)",""),
("N","Semantic time elements for build dates",""),
("S58","sitemap.xml","Every public route at https://quadcom.live, generated by tools/build-domain.py."),
("S58","Canonical link tags","On every indexable page; none on 404 or offline."),
("S58","og:image / og:url","Absolute URLs with a 1200x630 card (tools/build-og-card.mjs)."),
("D","Search Console / verification tags","Needs the domain and owner accounts."),
("R","Keyword stuffing",""),
("R","Hidden text for crawlers",""),
("R","Auto-generated doorway pages per term",""),
("R","Tracking parameters on internal links",""),
("R","Fake review/rating markup",""),
("R","Clickbait titles",""),
("R","Cloaking",""),
("R","Buying links",""),
]
AREAS["O · QUALITY, SECURITY & RELEASE"] = [
("S53","Review-agent gate before every export",""),
("S53","Route crawl (7 routes × phone/desktop): no 404s, no errors",""),
("S53","Desk visual audit across 4 views × 2 orientations",""),
("S54","Crawl extended to 404 and offline pages","tools/qa/crawl.mjs"),
("S54","Offline behaviour verified with the server stopped","tools/qa/offline.mjs: visited routes, desk with query, unvisited → offline page."),
("S54","Glossary behaviour tests (filter, count, /, Esc, ?q=, deep link)","tools/qa/glossary.mjs"),
("S54","This 600-item catalog with honest statuses",""),
("S54","Catalog generator validates 15 areas × 40 items",""),
("N","Content-Security-Policy for content pages","Pages use only same-origin scripts; inline skin script needs a hash."),
("N","CSP for the desk","Needs inventory of exchange endpoints and blob workers."),
("N","Subresource hashes for external resources","None today; keep it that way."),
("S58","Referrer-Policy: strict-origin-when-cross-origin","In _headers for every route."),
("S58","Permissions-Policy (camera, mic, geolocation off)","In _headers; payment and USB off too."),
("S58","X-Content-Type-Options nosniff guidance for host","In _headers, with X-Frame-Options and HSTS."),
("N","HTML validation in the release script",""),
("N","Link checker in the release script",""),
("N","Forbidden-word check in the release script",""),
("N","Automated screenshot diff per route",""),
("N","Desk visual audit in CI (headless)",""),
("N","GLIMMER kernel parity tests in CI",""),
("N","VISION golden images in CI",""),
("N","Release notes generated from the catalog",""),
("N","Semantic build numbers shared site/desk",""),
("N","Single source of truth for version strings",""),
("N","Dependency-free policy documented",""),
("N","Accessibility smoke test in CI (axe-core, local only)",""),
("S54","Desk visual audit ignores decorative aria-hidden overlays","The brand/dataRiver collision reported since V43 was a false positive."),
("N","Desk crash recovery test (kill tab mid-save)",""),
("N","Test matrix: Safari iOS, Chrome Android, Safari/Chrome/Firefox desktop",""),
("N","Threat model for local storage contents",""),
("D","Bug bounty","Needs an owner process."),
("D","Pen test","Needs production hosting."),
("D","SOC-style controls","No backend."),
("R","Shipping without a review gate",""),
("R","Disabling tests to go green",""),
("R","Secrets in the repository",""),
("R","eval() or remote code in pages",""),
("R","Third-party scripts without review",""),
("R","Force-pushing shared history without owner instruction",""),
("R","Marking unverified work as shipped",""),
]
