#!/usr/bin/env python3
"""Builds V55_COMPONENT_CATALOG.txt: app components for the QuadCOM site and desk.
Status: S56 / S55 shipped in that build (built and verified) · N next · D deferred (blocker given) · R rejected (reason given).
Fails unless there are 10 families of exactly 20 components (200 total)."""
import os
F = {}
F["NV · NAVIGATION"] = [
("S55","Bottom tab bar (phones)","HOME · LEARN · DESK · GLOSSARY · MORE; icon + label, gold active state, 52px targets, safe-area aware."),
("S55","Raised centre action (DESK orb)","Brushed-gold quad-diamond orb lifted out of the bar; the primary destination."),
("S55","Header compaction on phones","The 4-column header nav hands over to the tab bar; the header shrinks from 127px to 39px."),
("S55","MORE overflow sheet","Holds How it works, QuadCOM, Data and the Desk with one-line descriptions."),
("S55","No-JS fallback for MORE","Without JavaScript the MORE tab jumps to the footer, which lists every route."),
("S55","Complete footer route list","Home and QuadCOM added, so the fallback is exhaustive."),
("N","Icon-only compact tab bar variant","For landscape phones where labels crowd; labels stay as accessible names."),
("N","Tab badge (dot) for new content","Only for real, local events (a new build); never invented counts."),
("S56","Tab re-tap scrolls to top","Tapping the active tab returns the page to its top."),
("N","Tab bar hides on scroll down, returns on scroll up","Needs care so HALT-style controls never hide; site only."),
("N","Breadcrumb chip row under the title",""),
("N","Section jump chips (sticky) on long pages","Glossary letters as a horizontal chip rail."),
("N","Desk: bottom view switcher (CORE · FLEET · ALL · VISION)","Replaces the cycling VIEW button on phones; needs a desk layout pass."),
("N","Desk: swipe between views","Only with an explicit edge gesture; V43 D01 rejects ambiguous swipes beside charts."),
("N","Command palette (⌘K) on desktop","Routes, glossary terms and desk views."),
("N","Keyboard shortcut overlay ('?')",""),
("D","Tab bar inside the desk","Deferred: the desk is a full-screen cockpit with its own command bar and SITE button."),
("D","Deep-link router for desk panels","Needs stable panel ids across builds."),
("R","Hamburger drawer hiding every route","Rejected: the tab bar keeps primary routes visible."),
("R","More than five tabs","Rejected: labels become unreadable at 390px."),
]
F["SH · SHEETS & OVERLAYS"] = [
("S55","Bottom sheet (modal)","role=dialog, aria-modal, labelled title, rounded top, grab handle."),
("S55","Focus trap in sheets","Tab and Shift+Tab stay inside; the unchecked radio is skipped correctly."),
("S55","Esc, backdrop tap and close button dismiss","Focus returns to the control that opened the sheet."),
("S55","Drag-to-dismiss","Drag the handle or header down past 80px to close."),
("S55","Scroll lock while a sheet is open",""),
("S55","Reduced motion: sheets appear without sliding",""),
("N","Detents (half / full height)",""),
("S56","Glossary term preview sheet from any page","Tap an underlined term in Learn, How it works, QuadCOM or Data to read its definition in place."),
("N","Learn card quick-look sheet",""),
("N","Share sheet (Web Share API) with copy fallback",""),
("N","Confirm sheet for destructive desk actions (SEED, clear state)",""),
("N","Desk panel info sheet (what this panel is, its data class)","Observed / derived / inferred / model tag."),
("N","Popover for truncated desk values",""),
("N","Tooltip component (hover + long-press)",""),
("N","Full-screen dialog for the upgrade catalog","Searchable."),
("D","Nested sheets","Deferred until a flow needs them; stacking hurts orientation."),
("D","Picture-in-picture desk mini-view","Browser support and battery cost unclear."),
("R","Modal on page load","Rejected: interrupts before the reader acts."),
("R","Sheets that cannot be dismissed",""),
("R","Newsletter or install prompts in sheets","Rejected: no dark patterns."),
]
F["FB · FEEDBACK & STATUS"] = [
("S55","Toast system","Polite live region, icon + text + optional action, auto-dismiss, max three."),
("S55","Duplicate-toast guard","Flapping network events cannot stack identical messages."),
("S55","Link-copied toast","Replaces the inline COPIED text on anchor links."),
("S55","Offline / back-online toasts","'Offline · saved pages still open; nothing shown is live'."),
("S55","New-build toast with RELOAD action","Shown when an updated service worker takes over; never force-reloads."),
("S55","Skin change toast",""),
("S55","Reading-progress strip","2px gold strip on the header edge; only on pages longer than 1.5 screens."),
("N","Persistent offline chip in the header",""),
("N","Skeleton loaders for the desk's first paint",""),
("N","Inline form validation for the glossary search (e.g. too-short queries)",""),
("N","Empty-state illustrations (glossary no-match, offline)","Brand line art from the icon set."),
("N","Progress ring for GLIMMER calibration in the desk",""),
("N","Desk: feed-state pill (LIVE · FALLBACK · OFFLINE) with age","Observed state only."),
("N","Undo toast after SEED","Five-second window."),
("N","Error banner component with a Data-page link",""),
("N","Haptics on supported devices","Pairs with V43 D08 once severity semantics exist."),
("D","Push notifications","Needs a server and a consent design."),
("D","Sound cues","V43 D07: mute behaviour first."),
("R","Fake 'live users' or activity toasts","Rejected: fabricated social proof."),
("R","Toasts that steal focus","Rejected: the live region announces without moving focus."),
]
F["IN · INPUTS & CONTROLS"] = [
("S55","Segmented control (radiogroup)","REGALIA / OFF skin; arrow keys move and select; roving tabindex."),
("S55","Icon button (44px)","Used for sheet close."),
("N","Search field with clear button and result count","Upgrade of the V54 glossary search into a reusable component."),
("N","Toggle switch component",""),
("N","Chip filter group (glossary by class: QuadCOM / conventional)","Needs a class on every term first."),
("N","Stepper (desk horizon selection)",""),
("N","Slider with live value (VISION tier override)",""),
("N","Long-press menu on desk controls",""),
("N","Pull-to-refresh on content pages","Only reloads static content; never implies live data."),
("N","Copy button component (levels, links)",""),
("N","Disclosure (accordion) for Learn FAQs",""),
("N","Tabs component inside panels (desk ALL view sub-tabs)",""),
("N","Date/time display component with relative age",""),
("N","Keyboard-shortcut hint component (kbd)",""),
("N","Radio card list (choose a Learn path)",""),
("D","Voice input for search","Browser support and privacy review first."),
("D","Custom select replacing native select","Native is more accessible until a need appears."),
("R","Swipe-to-trade gestures","Rejected: interpretive output is not an order ticket."),
("R","Hold-to-confirm on HALT","Rejected: HALT must be instant."),
("R","Custom scrollbars that hide overflow cues",""),
]
F["DD · DATA DISPLAY"] = [
("N","Stat tile (label, value, provenance tag)","Shared by site and desk."),
("N","Provenance tag chip (OBSERVED · DERIVED · INFERRED · MODEL)","Already styled on the Data page; make it a component."),
("N","Sparkline component (desk champion NAV)",""),
("N","Mini gauge (odds ring) reused from VISION",""),
("N","Horizon rail component",""),
("N","Leaderboard row component with rank delta",""),
("N","Definition card (glossary term) component",""),
("N","Timeline component (build notes)",""),
("N","Diff badge (value up/down) with colour + arrow + text",""),
("N","Heat cell component (holdout map) with tooltip",""),
("N","Two-column key/value list (Data page)",""),
("N","Responsive table with sticky first column",""),
("N","Number formatter (US$ vs $, decimals per field)",""),
("N","Relative-time formatter ('3 min ago')",""),
("N","Empty value glyph ('—') component",""),
("D","Live price ticker on public pages","Deferred: needs a public data service; must never be simulated."),
("D","Embeddable desk widgets for other sites","Needs a read-only public API."),
("R","Price-strip widget with a fabricated value","Rejected: the 'Sell Wheat 2,20 £' pattern cannot show a real value on public pages."),
("R","P&L counters on the home page","Rejected: no fabricated live values."),
("R","3D charts","Rejected: distort quantities."),
]
F["MK · MARKET & DESK WIDGETS"] = [
("N","Trade ticket card (SIDE · ENTRY · SL · TP) as a reusable component","Read-only interpretation, labelled as model output."),
("N","Order-book depth ladder component",""),
("N","Risk meter (correlated risk / cap)",""),
("N","Crown card (top PicoProcessor)",""),
("N","Fleet balance bar (bull / bear) with numbers",""),
("N","Regime badge",""),
("N","Toxicity / VPIN pill",""),
("N","Scenario matrix cell",""),
("N","Horizon progress (short / medium / long)",""),
("N","Feed-age indicator next to the price","Observed; shows seconds since last tick."),
("N","Session summary card (local, end of session)",""),
("N","GLIMMER status chip (backend · envelope · pressure)","Exists in the desk; extract as a component."),
("N","VISION thumbnail card (links into the view)",""),
("N","PicoProcessor detail sheet",""),
("D","Alerts builder","Needs V43 D07/D08 semantics."),
("S56","Multi-asset switcher","Portrait desk bar (BTC · DOGE · XRP · LTC · DESKS) plus the /desk/ hub."),
("D","Portfolio across devices","Local-first policy (V43 D09)."),
("R","Buy/Sell buttons wired to an exchange","Rejected: out of scope; the desk is interpretive."),
("R","Leverage slider","Rejected: not a brokerage."),
("R","Social trading feed","Rejected: unverifiable and off-mission."),
]
F["SY · SYSTEM & PLATFORM"] = [
("S55","Icon set (SVG sprite, 15 symbols)","One file, currentColor, 24px grid; includes the QuadCOM quad-diamond desk mark."),
("S55","Service-worker update listener","Announces a new controller; the page is never swapped without consent."),
("S55","Icon sprite precached for offline",""),
("N","Install prompt card (only after two visits, dismissible forever)",""),
("S56","Storage usage card on the Data page",""),
("N","Clear-local-data control with confirm sheet",""),
("N","Theme-color sync with sheet open (darker status bar)",""),
("N","Standalone-mode detection adjusts header (no duplicate chrome)",""),
("N","Orientation hint for the desk on portrait tablets",""),
("N","Share target (receive links into glossary search)",""),
("N","App badge (navigator.setAppBadge) for a new build",""),
("N","Screen wake lock while the desk is open (opt-in)",""),
("N","Idle detection pauses GLIMMER work","Complements visibility handling."),
("S56","Offline route list component","The offline page lists the routes this device has saved."),
("D","Background sync of desk checkpoints","Limited support; needs a server."),
("D","Web NFC / Bluetooth integrations","No use case."),
("D","Home-screen widgets","Not available to web apps."),
("R","Fingerprinting for analytics","Rejected: privacy."),
("R","Forced update reloads","Rejected: announce and let the reader choose."),
("R","Silent background compute when hidden","Rejected: GLIMMER suspends."),
]
F["LR · LEARNING & ONBOARDING"] = [
("N","First-visit tour of the tab bar (three steps, skippable)",""),
("N","Desk coach marks (one per panel, opt-in)",""),
("N","Learn path cards (Operator · Curious · Technical)",""),
("N","Progress checklist for the Learn cards (local)",""),
("S56","Term-of-the-day card on Home (from the glossary)","Static rotation, no live data."),
("S56","Inline glossary highlights in Learn/Data copy",""),
("N","Worked-example stepper (tick → trade)",""),
("N","Quiz card (local, no accounts)",""),
("N","'What changed' card after an update",""),
("N","Printable operator primer component",""),
("N","Video/diagram card with transcript",""),
("N","Provenance explainer micro-card on desk panels",""),
("D","Guided desk tutorial mode","Needs stable desk selectors."),
("D","Certification","No accounts."),
("D","Localised onboarding","No locale planned."),
("R","Gamified streaks","Rejected: not an operator tool."),
("R","Mandatory onboarding","Rejected: always skippable."),
("R","Onboarding that fakes a trading session","Rejected: no fabricated values."),
("R","Pop-up hints on every visit",""),
("R","Onboarding that hides HALT",""),
]
F["BR · BRAND & MEDIA"] = [
("S55","Brushed-gold action orb","Uses the AURUM brushed texture; falls back to a gradient with the skin off."),
("S55","Filigree top edge on the tab bar (REGALIA)","Ornament only; removed with the skin off."),
("N","Animated mark on the orb for a new build (single pulse, reduced-motion aware)",""),
("N","SVG logo component (replaces the 632KB PNG)",""),
("N","Section divider component (filigree band)",""),
("N","Card corner ornament component (site + desk)",""),
("N","Provenance icons (observed, derived, inferred, model)",""),
("N","Empty-state line art set",""),
("N","OG image template (needs a domain)",""),
("N","Splash screens for all current iPhone sizes",""),
("N","Maskable icon review on Android launchers",""),
("N","Monochrome icon for iOS tinted home screens",""),
("N","Brand motion tokens (durations, easings)",""),
("N","Skin preview thumbnails in the skin control",""),
("D","Illustrated hero for Home","Needs an illustrator."),
("D","Sound identity","V43 D07."),
("D","Seasonal skins","After the token system."),
("R","Constant glow on the orb","Rejected: V43 D03."),
("R","Brand name of the reference skin","Rejected by owner instruction."),
("R","Stock photography",""),
]
F["LY · LAYOUT PRIMITIVES"] = [
("S55","Safe-area-aware fixed bottom region","Tab bar, TOP button and toasts clear the home indicator."),
("S55","Stacking order for fixed layers","Tab bar 40, sheet 60, toasts 70; the TOP button sits above the tab bar."),
("N","Stack / cluster / grid primitives as CSS utilities",""),
("N","Container-query card primitive",""),
("N","Sticky sub-header primitive",""),
("N","Split view (list + detail) for tablets",""),
("N","Masonry-free two-column content grid",""),
("N","Aspect-ratio media frame",""),
("N","Spacing tokens (4/8/12/16/24/32)",""),
("N","Radius tokens (sheet 14, control 9, card 0)",""),
("N","Elevation tokens for fixed layers",""),
("N","Z-index token map documented",""),
("N","Print layout primitives",""),
("N","Landscape phone layout for content pages",""),
("N","Foldable hinge-aware layout",""),
("D","Desk layout schema for user-arranged panels","V43 D10."),
("D","Multi-window desk","Needs the layout schema."),
("R","Fixed-height pages that clip content",""),
("R","Horizontal page scroll on phones","Rejected: V43 validation target."),
("R","Layout depending on JavaScript to be readable","Rejected: every page reads without JS."),
]
LABEL = {"S56": "SHIPPED V56", "S55": "SHIPPED V55", "N": "NEXT", "D": "DEFERRED", "R": "REJECTED"}
assert len(F) == 10
counts, lines, n = {k: 0 for k in LABEL}, [], 0
for fam, items in F.items():
    assert len(items) == 20, (fam, len(items))
    code = fam.split(" ")[0]
    lines.append(f"\n{fam}\n" + "─" * len(fam))
    for i, (s, t, note) in enumerate(items, 1):
        n += 1; counts[s] += 1
        lines.append(f"[{code}{i:02d}] {LABEL[s]:<11} {t}" + (f"\n{'':17}{note}" if note else ""))
assert n == 200
summary = "SUMMARY  " + " · ".join(f"{LABEL[k]} {v}" for k, v in counts.items()) + f" · TOTAL {n}"
head = ("QUADCOM ❖ GENESIS PUBLIC SITE — BUILD 55 APP COMPONENT CATALOG (UPDATED BUILD 56)\n\n"
        "200 app components in 10 families, each with an honest status. Shipped components are built into every\n"
        "site page and verified; the desk keeps its own cockpit chrome (see NV17). Public pages never show live values.\n")
open(os.path.join(os.path.dirname(__file__), "..", "V55_COMPONENT_CATALOG.txt"), "w").write(head + summary + "\n" + "\n".join(lines) + "\n")
print(summary)
