"""EVER NEXT axes: the ground-up dimensions every improvement item is composed from.

SURFACES  everything that exists in this repository, each tagged with what it is made of:
          route (a page), text, touch (interactive), data (shows market or model values), visual,
          motion, asset (a file others use), system (tooling or infrastructure).
ASPECTS   qualities to refine. `needs` lists tags; an aspect applies to a surface when they share one.
          Each aspect has six concrete moves ({s} is the surface) and escalating bars, one per cycle.
DEPTHS    the five stages that make every move improvable again.
"""

LAYERS = ["SITE PAGES", "SITE COMPONENTS", "DESK", "ASSETS", "SYSTEMS"]

SURFACES = [
    # id, name, layer, tags
    ("home", "the Home page", 0, "route text touch visual"),
    ("hub", "the Desks hub", 0, "route text touch visual"),
    ("learn", "the Learn page", 0, "route text touch visual"),
    ("how", "the How it works page", 0, "route text visual"),
    ("identity", "the QuadCOM page", 0, "route text visual"),
    ("datapage", "the Data page", 0, "route text data visual"),
    ("glossary", "the Glossary page", 0, "route text touch"),
    ("catalogpage", "the Catalog page", 0, "route text touch"),
    ("evernext", "the EVER NEXT page", 0, "route text touch data"),
    ("notfound", "the 404 page", 0, "route text touch"),
    ("offline", "the offline page", 0, "route text touch"),
    ("header", "the site header and primary nav", 1, "text touch visual"),
    ("tabbar", "the phone tab bar", 1, "touch visual text"),
    ("orb", "the raised DESK orb", 1, "touch visual"),
    ("more", "the MORE sheet", 1, "touch text visual motion"),
    ("toast", "the toast system", 1, "text visual motion"),
    ("search", "the search fields", 1, "text touch"),
    ("segment", "the segmented skin control", 1, "touch text"),
    ("termsheet", "the glossary term sheet", 1, "touch text motion"),
    ("pager", "the page-to-page pager", 1, "touch text"),
    ("footer", "the footer", 1, "text touch"),
    ("progress", "the reading-progress strip", 1, "visual motion"),
    ("totop", "the back-to-top control", 1, "touch visual"),
    ("chips", "the coin chips", 1, "touch visual"),
    ("deskcards", "the desk cards", 1, "text touch visual"),
    ("panel", "the content panel", 1, "text visual"),
    ("metricrow", "the metric rows", 1, "text data"),
    ("provtag", "the provenance tags", 1, "text data visual"),
    ("anchors", "the section anchor links", 1, "touch text"),
    ("azindex", "the A–Z index", 1, "touch text"),
    ("catfilter", "the catalog filters", 1, "touch text"),
    ("storagecard", "the device storage card", 1, "data text"),
    ("cmdbar", "the desk command bar and brand", 2, "touch text motion"),
    ("quote", "the headline price quote", 2, "data text"),
    ("chart", "the tape and price chart", 2, "data visual motion"),
    ("axis", "the chart axis labels", 2, "data text"),
    ("fleetbal", "the fleet balance cell", 2, "data text"),
    ("bullbear", "the bull / bear balance", 2, "data visual"),
    ("toppico", "the Top PicoProcessor panel", 2, "data text"),
    ("fundcells", "the fund cells", 2, "data text"),
    ("singular", "the Best Singular Trade", 2, "data text"),
    ("micro", "the microstructure panel", 2, "data text"),
    ("loss", "the loss control panel", 2, "data text"),
    ("leader", "the leaderboard", 2, "data text"),
    ("wall", "the processor wall", 2, "data visual motion"),
    ("book", "the order book", 2, "data text"),
    ("horizons", "the horizon rail", 2, "data visual"),
    ("vision", "the VISION view", 2, "data visual motion"),
    ("glimmersheet", "the GLIMMER sheet", 2, "touch text data"),
    ("deskbar", "the portrait desk bar", 2, "touch visual"),
    ("deskland", "the landscape desk layout", 2, "visual text"),
    ("deskport", "the portrait desk layout", 2, "visual text"),
    ("coins", "the coin marks", 3, "asset visual"),
    ("logo", "the official logo files", 3, "asset visual"),
    ("seal", "the Genesis Seal", 3, "asset visual"),
    ("intaglio", "the intaglio field", 3, "asset visual"),
    ("corners", "the quarter-diamond corners", 3, "asset visual"),
    ("band", "the guilloche band", 3, "asset visual"),
    ("bezel", "the reeded bezel", 3, "asset visual"),
    ("icons", "the icon sprite", 3, "asset visual"),
    ("ogcard", "the link-preview card", 3, "asset visual"),
    ("appicons", "the favicons and home-screen icons", 3, "asset visual"),
    ("splash", "the splash screens", 3, "asset visual"),
    ("regalia", "the REGALIA textures", 3, "asset visual"),
    ("aurum", "the AURUM textures", 3, "asset visual"),
    ("sw", "the service worker", 4, "system"),
    ("manifest", "the web app manifest", 4, "system"),
    ("headers", "the response headers", 4, "system"),
    ("deskgen", "the desk generator", 4, "system"),
    ("domaingen", "the domain stamper", 4, "system"),
    ("skingen", "the GENESIS skin generator", 4, "system"),
    ("coingen", "the coin master", 4, "system"),
    ("qa", "the QA suite", 4, "system"),
    ("storage", "on-device storage", 4, "system data"),
    ("feeds", "the market feed adapters", 4, "system data"),
    ("pricefmt", "price formatting", 4, "system data"),
    ("catalogs", "the catalogs", 4, "system text"),
    ("readme", "the README", 4, "system text"),
    ("glossarydata", "the glossary definitions", 4, "system text"),
    ("metadata", "the sitemap and page metadata", 4, "system"),
]

ASPECTS = [
    ("type", "TYPE SCALE", "text", [
        "List every font size used on {s} and map each to the type scale.",
        "Raise any text on {s} that renders below the legibility floor.",
        "Give {s} one line-height per size step instead of per element.",
        "Replace letter-spacing hacks on {s} with the size step that fits.",
        "Keep numerals on {s} tabular so digits never shift.",
        "Check {s} at 200% browser zoom for clipped or overlapping text."],
        ["body text ≥ 14px, labels ≥ 11px at 390px", "desk labels ≥ 7px rendered on iPhone 13", "every size is a scale token"]),
    ("contrast", "CONTRAST", "text visual", [
        "Measure every text and background pair on {s}.",
        "Raise any pair on {s} below the bar with a solid token colour, not opacity.",
        "Check {s} over each skin: GENESIS, REGALIA, AURUM and OFF.",
        "Check focus rings and borders on {s} against their backgrounds.",
        "Replace dimmed-by-opacity text on {s} with a named muted token.",
        "Check {s} in forced-colors (high contrast) mode."],
        ["4.5:1 body, 3:1 large text and UI edges", "7:1 body text (AAA)", "passes in forced-colors mode"]),
    ("spacing", "SPACING RHYTHM", "visual text", [
        "Record every margin and padding on {s} and map each to the 4px grid.",
        "Snap off-grid spacing on {s} to the nearest step.",
        "Make vertical rhythm on {s} consistent between siblings.",
        "Give {s} equal optical padding on all sides of its frame.",
        "Remove double spacing where borders and margins stack on {s}.",
        "Tokenise the spacing on {s} so a single change updates it everywhere."],
        ["4px grid", "named spacing tokens only", "rhythm identical at 390px and 1280px"]),
    ("align", "ALIGNMENT & GRID", "visual", [
        "Overlay the grid on {s} and note every element off it.",
        "Align the baselines of labels and values on {s}.",
        "Centre icons on {s} optically, not just by bounding box.",
        "Make edges of adjacent blocks on {s} share one line.",
        "Check {s} for half-pixel blur at DPR 2 and 3.",
        "Lock the column structure of {s} so content cannot shift it."],
        ["on the 12-column grid", "sub-pixel exact at DPR 3", "stable under live data changes"]),
    ("hierarchy", "HIERARCHY", "text", [
        "Name the single most important thing on {s} and check it reads first.",
        "Reduce competing emphasis on {s}: one hero per view.",
        "Order {s} so reading order matches visual order.",
        "Give headings on {s} a consistent level structure.",
        "Demote decorative labels on {s} below data labels.",
        "Test {s} with a five-second glance: what is remembered?"],
        ["one clear primary per view", "heading levels never skip", "glance test passes for a new visitor"]),
    ("touch", "TOUCH TARGETS", "touch", [
        "Measure every control on {s} and list any under the bar.",
        "Grow undersized targets on {s} with padding, not visual size.",
        "Separate adjacent targets on {s} so a thumb cannot hit two.",
        "Keep {s} controls clear of the home indicator and screen edges.",
        "Give {s} a pressed state that shows within one frame.",
        "Check {s} one-handed on a 390px screen."],
        ["44×44px targets", "8px between targets", "reachable one-handed"]),
    ("focus", "FOCUS & KEYBOARD", "touch", [
        "Tab through {s} and record the order and every trap.",
        "Give every control on {s} a visible focus ring.",
        "Make {s} fully usable with keyboard alone.",
        "Return focus to the trigger when {s} closes or changes view.",
        "Add arrow-key movement where {s} is a group.",
        "Check {s} with a switch-access tab order."],
        ["visible focus everywhere", "no traps, logical order", "arrow-key groups follow ARIA patterns"]),
    ("sr", "SCREEN-READER NAMING", "touch text data", [
        "Read {s} with VoiceOver and note every unnamed or misnamed element.",
        "Give each control on {s} an accessible name that matches its label.",
        "Hide decoration on {s} from assistive technology.",
        "Announce changes on {s} politely, and no more than needed.",
        "Give values on {s} their units in the accessible name.",
        "Add landmarks and headings so {s} can be navigated by rotor."],
        ["every control named", "live regions rate-limited", "full rotor navigation"]),
    ("motion", "MOTION DISCIPLINE", "motion", [
        "List every animation and transition on {s} with its duration.",
        "Remove any constant or looping motion from {s}.",
        "Honour reduced motion on {s} with an instant equivalent.",
        "Keep {s} motion under 250ms and tied to a user action.",
        "Animate {s} with transform and opacity only.",
        "Check {s} for layout shift during motion."],
        ["no infinite animation", "reduced motion honoured", "zero layout shift"]),
    ("weight", "WEIGHT & SPEED", "route asset visual", [
        "Measure the bytes {s} costs on first load.",
        "Cut the largest single cost of {s}.",
        "Serve {s} in a smaller format where one exists.",
        "Load {s} only when it is needed.",
        "Check {s} on a slow 3G profile.",
        "Set a byte budget for {s} and record it."],
        ["within the recorded budget", "budget cut by a quarter", "first render under 1s on 4G"]),
    ("offline", "OFFLINE", "route system", [
        "Open {s} offline after one visit and record what fails.",
        "Precache what {s} needs to render offline.",
        "Make {s} say clearly what is unavailable offline.",
        "Check {s} after a service-worker update while offline.",
        "Keep {s} usable when the network flaps.",
        "Test {s} offline in a fresh profile."],
        ["renders offline after one visit", "states what is unavailable", "survives an update while offline"]),
    ("empty", "EMPTY STATE", "data", [
        "Show {s} with no data yet and record what appears.",
        "Replace blank or zero-filled output on {s} with an honest empty state.",
        "Tell the user on {s} what will fill it and when.",
        "Keep {s} the same size empty as full, so nothing jumps.",
        "Distinguish 'none yet' from 'zero' on {s}.",
        "Test {s} on a brand-new desk with no history."],
        ["no zeros stand in for missing data", "same size empty and full", "explains what fills it"]),
    ("error", "ERROR & FAILURE", "data system", [
        "Break each input of {s} and record what happens.",
        "Make {s} fail visibly, never silently.",
        "Keep {s} usable when one source fails.",
        "Log failures of {s} where the operator can find them.",
        "Recover {s} automatically when the fault clears.",
        "Test {s} against malformed and out-of-range values."],
        ["never fails silently", "degrades per source", "recovers without a reload"]),
    ("stale", "STALENESS", "data", [
        "Record how {s} looks when its data stops updating.",
        "Show the age of the data on {s}.",
        "Dim or mark {s} once its data passes the stale threshold.",
        "Stop {s} extrapolating from stale data.",
        "Scale the stale threshold of {s} to its update rate.",
        "Test {s} with a feed paused for one, five and sixty minutes."],
        ["age always visible", "stale is marked within one interval", "no extrapolation past stale"]),
    ("precision", "NUMERIC PRECISION", "data", [
        "List every number on {s} with its decimals and units.",
        "Give prices on {s} decimals that suit the asset's magnitude.",
        "Use significant figures, not fixed decimals, for tiny values on {s}.",
        "Never let {s} round a real value to zero.",
        "Keep money, percentages and ratios on {s} in distinct formats.",
        "Test {s} at US$0.0006, US$0.20, US$100 and US$84,000."],
        ["correct for every listed asset", "no non-zero value shows as zero", "one formatter for every number"]),
    ("prov", "PROVENANCE", "data", [
        "Classify every value on {s}: observed, derived, inferred or model.",
        "Label model and inferred values on {s} as such.",
        "Show the source of observed values on {s}.",
        "Keep inferred values on {s} visually distinct from observed ones.",
        "Remove any value on {s} that has no real source.",
        "Link {s} to the Data page's definitions."],
        ["every value classified", "sources named", "nothing without a source"]),
    ("copy", "COPY CLARITY", "text", [
        "Read {s} aloud and mark every sentence that stumbles.",
        "Cut {s} copy to the shortest version that keeps the meaning.",
        "Replace jargon on {s} with a glossary link or plain words.",
        "Make labels on {s} say what a control does, not what it is.",
        "Check claims on {s} are literally true.",
        "Keep capitalisation and terms on {s} consistent with the glossary."],
        ["every claim literally true", "every term in the glossary", "readable by a new visitor"]),
    ("genesis", "GENESIS FIDELITY", "visual asset", [
        "Compare {s} under GENESIS with the skin's principles.",
        "Remove any glow, gradient noise or motion GENESIS does not allow from {s}.",
        "Make ornament on {s} derive from QuadCOM geometry.",
        "Keep ornament on {s} away from data ink.",
        "Check {s} under GENESIS at DPR 1, 2 and 3.",
        "Check {s} degrades cleanly to OFF."],
        ["engraved, static, derived", "crisp at every DPR", "OFF is complete and clean"]),
    ("darkroom", "DARK-ROOM LEGIBILITY", "text visual", [
        "View {s} at minimum screen brightness and note what disappears.",
        "Raise the faintest essential ink on {s}.",
        "Remove large bright areas from {s} that dazzle in the dark.",
        "Check {s} with night shift / true tone on.",
        "Keep status colours on {s} distinguishable when dim.",
        "Check {s} on an OLED screen for black crush."],
        ["legible at minimum brightness", "no dazzle areas", "status still distinct when dim"]),
    ("small", "SMALL SCREENS", "visual route", [
        "Render {s} at 320px wide and record every break.",
        "Stop anything on {s} forcing horizontal scroll.",
        "Reflow {s} instead of shrinking it.",
        "Check {s} with the largest accessibility text size.",
        "Keep primary actions of {s} visible without scrolling.",
        "Check {s} in split-screen and slide-over widths."],
        ["no breaks at 320px", "reflows at largest text", "works in split view"]),
    ("large", "LANDSCAPE & LARGE", "visual route", [
        "Render {s} in landscape and at 1920px and record wasted space.",
        "Cap line length on {s} for comfortable reading.",
        "Use the extra width on {s} for context, not stretch.",
        "Check {s} on an iPad in both orientations.",
        "Keep {s} centred and balanced on ultrawide screens.",
        "Check {s} with the browser at 50% and 200% zoom."],
        ["no wasted or stretched space", "comfortable line length", "balanced on ultrawide"]),
    ("print", "PRINT & EXPORT", "route text", [
        "Print {s} and note what is lost or wasted.",
        "Remove navigation and ornament from {s} in print.",
        "Keep {s} text black-on-white in print.",
        "Show link targets on {s} in print.",
        "Avoid page breaks inside blocks on {s}.",
        "Export {s} to PDF and check it reads well."],
        ["clean print", "links shown", "no split blocks"]),
    ("cvd", "COLOUR-BLIND SAFETY", "data visual", [
        "View {s} through protanopia, deuteranopia and tritanopia filters.",
        "Pair every colour meaning on {s} with a shape, sign or word.",
        "Check up/down on {s} are distinguishable without red and green.",
        "Keep chart series on {s} separable in greyscale.",
        "Check {s} status dots have a text equivalent.",
        "Test {s} with a colour-blind reviewer."],
        ["meaning never colour-only", "separable in greyscale", "reviewed by a colour-blind user"]),
    ("locale", "LOCALE READINESS", "data text", [
        "List every hard-coded format on {s}: currency, decimals, dates.",
        "Format numbers on {s} through one locale-aware function.",
        "Keep {s} layout intact with longer translated labels.",
        "Use unambiguous dates and times on {s}.",
        "Mark the language of every text part on {s}.",
        "Check {s} with a comma decimal separator."],
        ["one formatter", "tolerates 40% longer labels", "language marked"]),
    ("determinism", "DETERMINISM", "system asset", [
        "Rebuild {s} twice and diff the outputs.",
        "Remove timestamps and randomness from {s} output.",
        "Pin every input {s} depends on.",
        "Make {s} fail loudly on unexpected input.",
        "Record the exact command that produces {s}.",
        "Check {s} rebuilds the same on another machine."],
        ["byte-identical rebuilds", "fails on drift", "same on any machine"]),
    ("tests", "TEST COVERAGE", "system route touch data", [
        "List what {s} does and which QA script checks each part.",
        "Add a QA check for the riskiest untested part of {s}.",
        "Make the QA checks for {s} fail with a clear message.",
        "Run the QA for {s} at 390px and 1280px.",
        "Add a regression test for the last bug found in {s}.",
        "Time the QA for {s} and keep it fast."],
        ["riskiest part checked", "every past bug has a test", "suite under five minutes"]),
    ("docs", "DOCUMENTATION", "system asset", [
        "Check the README explains {s} in one paragraph.",
        "Document why {s} exists, not just what it does.",
        "Give {s} a worked example.",
        "List the invariants {s} must keep.",
        "Record known limits of {s} honestly.",
        "Check the docs for {s} still match the code."],
        ["one clear paragraph", "invariants listed", "docs match code"]),
    ("security", "SECURITY & PRIVACY", "system route", [
        "List what {s} stores, sends and receives.",
        "Remove any data {s} does not need.",
        "Check {s} under the site's response headers.",
        "Keep {s} free of third-party requests it does not need.",
        "Validate every external value {s} accepts.",
        "Review {s} against a content-security policy."],
        ["minimal data", "valid under strict headers", "passes a CSP"]),
    ("caching", "CACHING & DELIVERY", "system asset route", [
        "Record how {s} is cached by the browser and the service worker.",
        "Version {s} so a new build replaces it.",
        "Make {s} revalidate without blocking render.",
        "Check {s} after two deploys in a row.",
        "Precompress {s} where the host allows.",
        "Keep {s} cacheable for as long as it is immutable."],
        ["new builds always reach users", "never blocks render", "immutable assets cached long"]),
    ("consistency", "CONSISTENCY", "visual text touch", [
        "Compare {s} with its nearest sibling and list differences.",
        "Replace one-off values on {s} with shared tokens.",
        "Make {s} behave like every other control of its kind.",
        "Match {s} corner radii, borders and weights to the system.",
        "Remove duplicate CSS rules that style {s}.",
        "Count !important rules affecting {s} and cut them."],
        ["no one-off values", "no duplicate rules", "no !important wars"]),
    ("resilience", "RESILIENCE", "system data", [
        "Kill {s} mid-operation and record the state it leaves.",
        "Make {s} restart cleanly after a crash.",
        "Bound every queue and buffer in {s}.",
        "Keep {s} within memory on an old phone.",
        "Survive a storage-quota error in {s}.",
        "Run {s} for 24 hours and check for drift or leaks."],
        ["clean restart", "bounded resources", "24-hour soak clean"]),
    ("craft", "CRAFT DETAIL", "visual asset", [
        "Inspect {s} at 400% zoom and list every imperfection.",
        "Fix the smallest visible flaw on {s}.",
        "Check {s} antialiasing on light and dark backgrounds.",
        "Align {s} to whole pixels at every DPR.",
        "Balance the optical weight of {s} with its neighbours.",
        "Compare {s} with the best reference you know and close one gap."],
        ["no visible flaw at 100%", "no flaw at 400%", "stands beside the best reference"]),
]

DEPTHS = [
    ("OBSERVE", "Record every instance first; change nothing yet."),
    ("REFINE", "Fix each recorded instance."),
    ("SYSTEMATISE", "Turn the fix into a shared token, rule or component used everywhere it applies."),
    ("PROVE", "Add an automated QA check that fails if it regresses."),
    ("SUSTAIN", "Wire the check into the generators so no build can ship without it."),
]
